version: '3.1'
services:
  nfd-discord-api-dev:
    image: dottjt/nfd-discord
    container_name: 'nfd-discord-api-dev'
    build:
      context: ../../../
      dockerfile: ./deployment/docker/dev/Dockerfile
    ports:
      - 2000:2000
      - 2001:2001
    depends_on:
      - nfd-discord-postgres-dev
    restart: always
    env_file:
      - ../../environment/.env.development
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
    networks:
      - docker-network-discord-dev

  nfd-discord-postgres-dev:
    image: postgres:alpine
    container_name: 'nfd-discord-postgres-dev'
    ports:
      - 2346:5432
    restart: always
    volumes:
      - "../../../volumes/postgres:/var/lib/postgresql/data"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ../../environment/.env.development
    networks:
      - docker-network-discord-dev

networks:
  docker-network-discord-dev:
    driver: bridge
