language: node_js
node_js:
  - "10"
sudo: enabled
addons:
  ssh_known_hosts: 198.199.67.180
branches:
  only:
  - master
services:
- docker
env:
  global:
  - secure: V1UHrtiBD6tU2/LOKFpxblOtR3HapCBHlyxWxk6mEZE6Q0O2qmkggKVgVY8qBMjKmTzrYzjvxw3h9mH5LgDbSqQ9Eu9IPhL7QPfqBVvkVXs59OqdmnXNhzq9qR86CRFITfNyr3HEUjLWVl7QF0hKeZtmm9RhICVpK6kUzpmH/zTN9i11t7d/Uia79M+vzrOQlsMwya54k4famHigZrJp44+6Ao3Ov/GI4cHYjWuHHZLKNa0MhTkD+EmKek+4hZzFlQP2iPqVpvjxrjDomOGAO6wNSv1+c1afRmV7vM7Zsih7Q5vDOEK17PEwfGJ2fosvGbIQz8skeEHvsRZZHhLLostOW7mkpcz+TtUJTsPm2Yy6KK3l92L4FWasWFHLcQfeo71Sm/oAkKuzfIAFCm/5YgYItrW6Oi8MZSuq5i/3KXhZ/ni5Zc+QdwDAcxW3SnhaAkuOmmOu8wGmxXhF0NQvGTCll1VzwzbYEXGpWspTJhMTNY1nNT6dAK6XMDTP/xtVIcUzTZr3Y9ZOOmal2uRcyji4DWQPSOyA1i+PRU4odZEv93wbSsRjF5DrJ1dZzBoUYYJwMvUqT6enovv35ZFBVMe1PXwd0AnJ2J+qlerVVuXKVCJrWMHihZvn4fn+qylGvEYrY59maVLeIDlTMLOr+80lMw3/SVjHCWpIJph5SMo=
  - DOCKER_USERNAME=dottjt
  - SERVER_IP_ADDRESS=198.199.67.180
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull dottjt/nfd-discord || true
script:
- ls -a
- echo "$AWS_ACCESS_KEY"
- docker-compose build nfd-discord
after_script:
- docker images
before_deploy:
- openssl aes-256-cbc -K $encrypted_989cc8ced1db_key -iv $encrypted_989cc8ced1db_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
deploy:
- provider: script
  script: docker push dottjt/nfd-discord
  on:
    branch: master
- provider: script
  script: bash deploy.sh
  on:
    branch: master

