version: '3'
services:
  
  nfd-discord-api:
    image: dottjt/nfd-discord
    container_name: 'nfd-discord'
    ports:
      - 2000:2000
    networks:
      - docker-network
    depends_on:
      - nfd-discord-postgres

  nfd-discord-postgres:
    image: postgres:alpine
    container_name: 'nfd-discord-postgres'
    ports:
      - 2345:2345
    volumes:
      - ./nfd-discord-postgres:/var/lib/postgresql/data:rw
    restart: always
    env_file:
      - .env

    environment:
      - POSTGRES_USER=deploy
      - POSTGRES_PASSWORD=deploy
      - POSTGRES_DB=watashi_api

networks:
  docker-network:
    driver: bridge
